// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cngslbtadxahipmuwftu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuZ3NsYnRhZHhhaGlwbXV3ZnR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwOTk4ODEsImV4cCI6MjA3NTY3NTg4MX0.4yGID7O7j5q1e2tsR1khri0QCl0wQ0xG5su2Je1GbEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});